---
# RulesUI plugin config
# Created by SkullyGamingDM

# Use "{player}" to display player name
# Use "ยง" as formatting codes
# Use "\n" to break into a new line

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: 1.2
#######################

##### COMMAND SETTINGS #####
# Change the command description that will be shown in help pages and command suggestions
# Leave empty to use the default command description
command-desc: ""
# Add command aliases for /rules command (Leave empty if you don't want to add command aliases)
# Do not use "/" in front of the commands!
command-aliases: []
#############################

# Set the RulesUI title here:
title: "RulesUI"

# Set the RulesUI content here:
content: "Change in config.yml!"

# Set the RulesUI button here:
button: "Ok"

# Whether to check for plugin updates (Recommended)
check-updates: true
...
